kind: Deployment
apiVersion: apps/v1
metadata:
  name: netlifycms-auth
  namespace: twitchmidi
  labels:
    app: netlifycms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netlifycms-auth
  template:
    metadata:
      labels:
        app: netlifycms-auth
    spec:
      containers:
        - name: netlifycms-auth
          image: rafaelpernil/netlifycms-auth
          imagePullPolicy: Always
          env:
          - name: OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: netlifycms-auth-secret
                key: OAUTH_CLIENT_ID
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: netlifycms-auth-secret
                key: OAUTH_CLIENT_SECRET
          - name: ORIGIN
            valueFrom:
              secretKeyRef:
                name: netlifycms-auth-secret
                key: ORIGIN
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3000
      restartPolicy: Always
