kind: Service
apiVersion: v1
metadata:
  name: netlifycms-auth
  namespace: twitchmidi
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: netlifycms-auth
  type: LoadBalancer
